# Site settings
title: Creative with Code
email: creator@createwithcode.com
description: > # this means to ignore newlines until "baseurl:"
 Get creative with code. We're about experimenting with new front end web technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: creativewithcode
github_username:  creativewithcode

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Github
    link: https://github.com/GraemeFulton/graemefulton.github.io
  option2:
    name: Twitter
    link: http://twitter.com/graeme_fulton

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-archives

exclude: [Rakefile]

#jekyll archives
# jekyll-archives:
#   enabled:
#     - categories
#     - posts
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
